const books = [
    {
        id: 1,
        name: "Digital Minimalism",
        author: "Cal Newport",
        category: "Produtividade",
        pages: 254,
        recommend: false,
        read: false,
    },
    {
        id: 2,
        name: "Padrões Javascript",
        author: "Stoyan Stefanov",
        category: "Tecnologia",
        pages: 231,
        recommend: false,
        read: true,
    },
    {
        id: 3,
        name: "Ele ainda remove pedras",
        author: "Max Lucado",
        category: "Cristão",
        pages: 230,
        recommend: true,
        read: true,
    },
    {
        id: 4,
        name: "Derrubando Golias ",
        author: "Max Lucado",
        category: "Cristão",
        pages: 164,
        recommend: true,
        read: true,
    },
    {
        id: 5,
        name: "O Genocídio do negro brasileiro",
        author: "Abdias do Nascimento",
        category: "Historia Brasileira",
        pages: 254,
        recommend: false,
        read: false,
    },
    {
        id: 6,
        name: "Código Limpo",
        author: "Robert C. Martin",
        category: "Tecnologia",
        pages: 315,
        recommend: true,
        read: true,
    },
    {
        id: 7,
        name: "Nunca Desista",
        author: "Joyce Meyer",
        category: "Cristão",
        pages: 280,
        recommend: true,
        read: true,
    },
    {
        id: 8,
        name: "Esperença Inabalavel",
        author: "Max Lucado",
        category: "Cristão",
        pages: 280,
        recommend: true,
        read: true,
    },
    {
        id: 9,
        name: "As veias abertas da América Latina",
        author: "Eduardo galeano",
        category: "Américas",
        pages: 400,
        recommend: false,
        read: false,
    },
    {
        id: 10,
        name: "Algoritimos para viver",
        author: "Brian Christian",
        category: "Tecnologia",
        pages: 412,
        recommend: true,
        read: true,
    }
]

module.exports = books;